### ISSUE TITLE
Auth0 context component send error when using Vite .env system

### ISSUE THREAD

**Issue by excessivecoding** [rturnq/solid-auth0#7]
At the moment, Typescript is sending warning/error when using the package with Vite.js dotenv system.

e.g.:
```jsx
    <Auth0
      domain={import.meta.env.VITE_AUTH0_DOMAIN} // This is sending an error
      clientId={import.meta.env.VITE_AUTH0_CLIENT_ID} // This is sending an error
    >
      <Router routes={routes}>
        <App />
      </Router>
    </Auth0>
```

Vite.js `import.meta.env.VAR` is actually sending value as `string|boolean` which doesn't match the component props types

## Workaround

It's possible to fix with `as string`

```jsx
    <Auth0
      domain={import.meta.env.VITE_AUTH0_DOMAIN as string} // No error anymore
      clientId={import.meta.env.VITE_AUTH0_CLIENT_ID as string} // No error anymore
    >
      <Router routes={routes}>
        <App />
      </Router>
    </Auth0>
```

## Possible solution

Maybe the package could allow `string|boolean` to match Vite.js dotenv system, as it's becoming the default for Solid Starter and other project.

Throwing an error might also be useful, as the component will not work without proper setup and this could give extra information to the user.

**Comment by rturnq** [comment]
Hmm, I don't really think the component should accept booleans here as those props are essentially defined by what the auth0-spa package accepts. Widening the types here would suggest to users they can pass in booleans only to have it fail immediately during runtime.

I wonder if using a [type definition](https://vitejs.dev/guide/env-and-mode.html#intellisense) for the env vars might be a solution for you when using Vite.

**Comment by excessivecoding** [comment]
Oh, I didn't know about type definition, I guess it makes more sense then.

Thanks for taking the time to reply 🙏

Closing this
